### PR TITLE
Some code is duplicated in the examples. Move it to a dedicated module

### PR DESCRIPTION
**Pull request by mathrack**

### CODE REVIEW

**Comment by pbartholomew08** [comment]
My suggestion would be to put this in something like `examples/utilities.f90` - otherwise we risk imposing an argument count/ordering on users (who may have other arguments they need to pass).

**Comment by mathrack** [comment]
Currently, the processing of the command-line arguments ships inside the library 2decomp. It is present in the library only when it is compiled with the tests.

It makes sense to move the file outside of s`src` and to put it inside a folder such as `examples/utilities` or similar.

Are you also suggesting to move it outside of the library 2decomp ?

**Comment by rfj82982** [comment]
I am in favour of something inside `examples`. I do not want an extra module in `src` since here we should have only 2DECOMP&FFT mandatory modules/code.

**Comment by pbartholomew08** [comment]
I would make it not part of the library, I would have it as a utilities module that is compiled as part of the test suite only

**Comment by mathrack** [comment]
This is ready for review

**Comment by pbartholomew08** [comment]
I think we can use a cmake interface library (not sure if that's exactly the name) - I can take a look later (probably tomorrow) at doing this.

**Comment by rfj82982** [comment]
I’ll have a look as well

**Comment by pbartholomew08** [comment]
I have a fix that builds in parallel locally in #265

**Comment by pbartholomew08** [comment]
> I think we can use a cmake interface library (not sure if that's exactly the name) - I can take a look later (probably tomorrow) at doing this.

The CMake terminology is "Object Library" - it allows you to bundle up object files and treat them logically like a library so that the correct dependencies can be specified.

**Review by pbartholomew08 — APPROVED** [review]
I think this looks good assuming the CI passes

**Comment by pbartholomew08** [comment]
Looks like this might have been merged prematurely, failing on the MPICH build test
```
/usr/bin/mpif90.mpich -cpp -std=f2008 -ffree-line-length-none -fallow-argument-mismatch -DDEBUG -g3 -Og -ffpe-trap=invalid,zero -fcheck=all -fimplicit-none -Wall -Wno-unused-function -Wno-integer-division CMakeFiles/init_test.dir/init_test.f90.o ../CMakeFiles/examples_utils.dir/utilities.f90.o -o ../../bin/init_test  ../../lib/libdecomp2d.a ../../lib/libdecomp2d.a 
```
I reckon due to twice linking `libdecomp2d.a`

**Pull request merged**
