### PR TITLE
Fix parallel make

### PR DESCRIPTION
**Pull request by mathrack**

### CODE REVIEW

**Review by rfj82982 — APPROVED** [review]
LGTM

**Comment by rfj82982** [comment]
I'll merge this and after I'll have a look at the tests that are failing. If we cannot fix quickly the part with ADIOS I would suggest to remove them from the CI (or keep only 1 CI with them) to avoid all this plethora of failed tests, that in essence is just a single aspect of the library. Let me know what do you think? Maybe we can have a CI just for ADIOS with all the compilers in it

**Comment by rfj82982** [comment]
Yes this is also an option

**Comment by rfj82982** [comment]
Just merging the main first check that only ADIOS test are failing and after merge

**Comment by mathrack** [comment]
I will open a dedicated PR to skip running the ADIOS2 CI tests. We can talk about the CI tests at the beginning of the next week

**Pull request merged**
