### PR TITLE
Minor refactoring in transpose subroutines

### PR DESCRIPTION
**Pull request by mathrack**
Re-open https://github.com/2decomp-fft/2decomp-fft/pull/219

### CODE REVIEW

**Comment by mathrack** [comment]
@rfj82982 please take a quick look at this draft PR.

In my opinion it makes the code of the transpose routines slightly simpler. Please let me know if this could be relevant. If yes, I will apply similar modifications to the other transpose subroutines and switch from draft to regular PR.

**Comment by mathrack** [comment]
I think this PR could be extended to fuse CPU and GPU buffers

**Review by rfj82982 — APPROVED** [review]
Run some extra tests on multi-GPUs and everything seems ok.

**Comment by mathrack** [comment]
This was a draft PR. Only the X=>Y transpose subroutines are included.

I will revert the merge.

The PR should update all the transpose subroutines, not only the X=>Y ones.

**Comment by mathrack** [comment]
Please revert. I will include the other transpose subroutines in this PR later.

**Comment by rfj82982** [comment]
Ok I'll finish off everything before the proper merge.

**Pull request merged**
