### PR TITLE
Update adios2_config.xml for grad3d test

### PR DESCRIPTION
**Pull request by pbartholomew08**
Remove unused io handles and match io handle name with code

Merge into #283

### CODE REVIEW

**Comment by rfj82982** [comment]
@pbartholomew08 , thanks I think you sorted the error I had with ADIOS2

**Comment by rfj82982** [comment]
Ok the issue with ADIOS2 is still there. Do you want me to have a look?

**Comment by rfj82982** [comment]
the error i got is the following 
```
[Tue Nov 07 09:33:26 2023] [ADIOS2 ERROR] <Helper> <adiosSystem> <ExceptionToError> : adios2_at_io: [Tue Nov 07 09:33:26 2023] [ADIOS2 EXCEPTION] <Helper> <adiosType> <CheckForNullPtr> : found null pointer for adios2_adios, in call to adios2_at_io

 2DECOMP&FFT ERROR
   errorcode:                4
   error in file  /home/rfj82982/GIT_Work/2decomp-fft/src/io.f90
            line          1878
   error message: adios2_at_io grad-io
 2DECOMP&FFT ERROR
   errorcode:                4
   error in file  /home/rfj82982/GIT_Work/2decomp-fft/src/io.f90
            line          1878
   error message: adios2_at_io grad-io
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 4.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by pbartholomew08** [comment]
If the tests pass I think this should now be good to go

**Comment by rfj82982** [comment]
Yes I am looking at the runner

**Review by rfj82982 — APPROVED** [review]
LGTM

**Pull request merged**
